### ISSUE TITLE
https://steamcommunity.com/sharedfiles/filedetails/?id=2812783478

### ISSUE THREAD

**Issue by KrakenTales** [omaremad74/omaremad74.github.io#1]
Hello!
I can't find next string in [your workshop's mod,](https://steamcommunity.com/sharedfiles/filedetails/?id=2812783478) although I got that message in game's console:
```
"print("MODDED SKINS WARNING:\n\t",
"You are creating skins for official entities. This is permitted for local mods to make testing easier\n\t",
"If you have not yet been curated however, please contact Hornet. Otherwise your mod WILL crash as a workshop release")"
```
Could you help me find the way to hide some part of codes in mod like you? Or is that implemented somewhere in game?

**Comment by KrakenTales** [comment]
No chance to be answered?

**Comment by omaremad74** [comment]
> No chance to be answered?

Hi, I'm terribly sorry for the late response, I had not seen this issue be posted at the time.
I'm a bit confused to what you are asking. Are you looking to skin official entities?

**Comment by KrakenTales** [comment]
I thought that my comment looked barbaric from the side, that's why there was no answer ;D that's all right, thank you for responding!
I recently discovered [your mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2812783478), I wanted to try it together with my own, not yet ready for release. An error occurred during the experiment:
```
"MODDED SKINS WARNING:
You are creating skins for official entities. This is permitted for local mods to make testing easier,
If you have not yet been curated however, please contact Hornet. Otherwise your mod WILL crash as a workshop release"
```
I tried to find what causes it, but did not find the text from the console in the mod itself. I never found out where this message came from, because it is logical to assume that since the message appeared along with the mod, then it probably came with the mod. I would like to know how to remove plain text messages from the mod, while making them appear in the game after certain actions. Is it ever possible without modifing binary game files?

**Comment by omaremad74** [comment]
> I thought that my comment looked barbaric from the side, that's why there was no answer ;D that's all right, thank you for responding! I recently discovered [your mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2812783478), I wanted to try it together with my own, not yet ready for release. An error occurred during the experiment:
> 
> ```
> "MODDED SKINS WARNING:
> You are creating skins for official entities. This is permitted for local mods to make testing easier,
> If you have not yet been curated however, please contact Hornet. Otherwise your mod WILL crash as a workshop release"
> ```
> 
> I tried to find what causes it, but did not find the text from the console in the mod itself. I never found out where this message came from, because it is logical to assume that since the message appeared along with the mod, then it probably came with the mod. I would like to know how to remove plain text messages from the mod, while making them appear in the game after certain actions. Is it ever possible without modifing binary game files?

You would be correct that print is from the API! It is there to let mod developers know if they are creating skins for official entities/clothing curios. Is your complaint that it's being spammed too much in the console/log? I'll be happy enough to change that! I actually felt it was way too spamm-y too and have been meaning to get around to adjusting it slightly to make it more periodic which I might be able to get in the next workshop update to the API.

**Comment by KrakenTales** [comment]
Do I understand correctly that this mod (api) interacts with the code that is located somewhere in the game's libraries themselves (dll or exe)?
The mod that I have been working on for a very long time, due to inferior performance and the lack of all the desired features, has not been able to be published yet. Based on the message I received in the console, I think that my mod seems to be using prohibited functions. Your mod seems neater to me, but at the same time "difficult" for the novice modder that I consider myself to be.
Can you help me find out, if it's possible, which function of the api is causing that error or how it is checked by the api, so that I can identify the shortcomings myself and fix as expected?
Perhaps it would be nice to allow the end user to edit the error message themselves, so that the length could be customized to the size necessary for their needs. The occurrence of the message itself is useful, so you can use your old WIP stuff and if there is something unacceptable, then the api will be able to hint that something went wrong at least.

**Comment by omaremad74** [comment]
> Do I understand correctly that this mod (api) interacts with the code that is located somewhere in the game's libraries themselves (dll or exe)? The mod that I have been working on for a very long time, due to inferior performance and the lack of all the desired features, has not been able to be published yet. Based on the message I received in the console, I think that my mod seems to be using prohibited functions. Your mod seems neater to me, but at the same time "difficult" for the novice modder that I consider myself to be. Can you help me find out, if it's possible, which function of the api is causing that error or how it is checked by the api, so that I can identify the shortcomings myself and fix as expected? Perhaps it would be nice to allow the end user to edit the error message themselves, so that the length could be customized to the size necessary for their needs. The occurrence of the message itself is useful, so you can use your old WIP stuff and if there is something unacceptable, then the api will be able to hint that something went wrong at least.

The mod can not do anything with the games engine, nor can other mod, only the LUA parts of the game can be touched. What a power it would be to touch the engine though!

We allow mods to skin vanilla content such as items and characters with some restrictions, for example the Prison outfits mod adds skins for the football helmet and boomerang + some custom clothing(This whitelist that you can see is part of these restrictions!). Reason we have restrictions is so that we do not interfere with Kleis own skins, it is important as skins are Kleis main monetary gain from Don't Starve Together. If you're getting this print then it means you're skinning official/vanilla content or custom curios. I would be happy enough to help you through this and conforming to the simple restrictions 🙂. It might be better for us to continue on a place like Discord if you have an account there and we can discuss your mod.

I'll be happy enough to allow the error message from the API to be edited easily too! Likely in the next workshop update.

**Comment by KrakenTales** [comment]
This mod, in my opinion, can make you believe in probably impossible things at least. I understand that it works like an api (I understand that it is an api anyway), but it seems that my knowledge is limited to the fact that the api should interact, if not with local data, then with remote, with "server" code. When the Internet is disabled, the same message comes, I suppose this indicates that the api interacts with local data. But locally, the location of the message itself was nowhere to be found in order to find out how the error was formed. Could you point me to a function directly in the mod causes a message? (guess this question is probably posed stupidly)
I have not seen the white list, is it also somewhere?
It looks like the problem may indeed be related to skins, since there are some prefabs that I tried to change the skin for events that are related to the mod. I am like in a web, which I have not yet learned to weave, but so far only get confused and miraculously solve some difficulties.
If you have time, I will be glad for your help in the discord. _**KrakenTales#5471**_
Thank you for your feedback ;)
